In [1]:
import easypheno
import os
import pathlib
import numpy as np
import pandas as pd

In [2]:
genos = pd.read_csv("data/test_data/genos_reduce.csv")

In [3]:
genos

RIL  PZA01271.1  PZA03613.1  PZA02129.1  PZA02032.1  PHM2244.142  \
0   Z001E0001           0           0           0           0            0   
1   Z001E0002           2           2           2           2            2   
2   Z001E0003           0           0           0           0            0   
3   Z001E0004           0           0           0           0            0   
4   Z001E0005           0           0           0           0            0   
5   Z001E0006           2           2           2           2            2   
6   Z001E0007           2           2           2           2            2   
7   Z001E0008           0           0           0           0            0   
8   Z001E0009           2           2           2           2            2   
9   Z001E0010           0           0           0           0            0   
10  Z001E0103           2           2           2           2            2   
11  Z001E0104           0           0           0           0            0   
12  Z001E0105           0           0           0           0            0   
13  Z001E0106           2           2           2           2            2   
14  Z001E0107           2           2           2           2            2   
15  Z001E0108           0           0           0           0            0   
16  Z001E0109           0           0           0           0            2   
17  Z001E0110           0           0           0           0            0   
18  Z001E0111           2           2           2           2            2   
19  Z001E0112           2           2           2           2            2   
20  Z002E0007           0           0           0           0            0   
21  Z002E0008           2           2           2           2            2   
22  Z002E0009           2           2           2           2            2   
23  Z002E0010           2           2           2           2            2   
24  Z002E0011           2           2           2           2            2   
25  Z002E0012           2           2           1           0            0   
26  Z002E0013           2           2           2           2            2   
27  Z002E0014           2           2           2           2            2   
28  Z002E0015           0           0           0           0            0   
29  Z002E0016           2           2           2           2            2   
30  Z002E0108           2           2           2           2            2   
31  Z002E0109           2           2           2           2            2   
32  Z002E0110           2           2           2           2            2   
33  Z002E0111           0           0           0           0            0   
34  Z002E0112           0           0           1           2            2   
35  Z002E0113           0           0           0           0            0   
36  Z002E0114           0           0           0           0            0   
37  Z002E0115           2           2           2           2            2   
38  Z002E0116           2           2           2           2            2   
39  Z002E0117           0           0           0           0            0   
40  Z003E0012           0           0           0           0            0   
41  Z003E0013           0           0           0           0            0   
42  Z003E0014           0           0           0           0            0   
43  Z003E0016           0           0           0           0            0   
44  Z003E0017           2           2           2           2            0   
45  Z003E0018           2           2           2           2            2   
46  Z003E0019           0           0           0           0            0   
47  Z003E0020           2           2           2           2            2   
48  Z003E0021           0           0           0           0            0   
49  Z003E0022           0           0           2           2            2   

    PZA02372.1  PHM6238.36  PZA

In [4]:
genotypes = genos.iloc[:,1:50].to_numpy()
SNP_ids = genos.columns[1:].to_numpy()
sample_ids = genos.iloc[:,0].to_numpy()

In [5]:
sim_pheno = easypheno.simulate.synthetic_phenotypes.get_simulation(X = genotypes, sample_ids = sample_ids, snp_ids = SNP_ids,
                                                      number_of_samples = 50, number_causal_snps = 2,
                                                      explained_variance = 80, maf = 30, heritability = 80,
                                                      seed = 42, number_background_snps = 1, distribution = "normal",
                                                      shape = 0.5)

In [6]:
#sim snp values
sim_pheno[0]

array([ 0.07156002, -0.01397921, -0.040426  ,  0.07380458,  0.01187991,
        0.09612826,  0.09625086,  0.04699002,  0.07817087,  0.03297406,
        0.06408823,  0.09419974, -0.01122891,  0.06811163,  0.08520039,
        0.03465107, -0.08571908,  0.16946414,  0.09615379,  0.06327065,
        0.02170373,  0.1436353 ,  0.02443042,  0.00505192,  0.10594065,
        0.06625969, -0.03146853,  0.01537757,  0.07771958, -0.0260593 ,
       -0.01750206,  0.02104089,  0.09038075,  0.09998524,  0.01974403,
        0.06093298,  0.10132147,  0.08219813,  0.03286569,  0.05844026,
        0.0671134 ,  0.08452965, -0.00815651,  0.11115621,  0.06985673,
        0.01729826,  0.09325974,  0.0677881 ,  0.08690871,  0.0200444 ])

In [7]:
#sample ids
sim_pheno[1]

array(['Z003E0012', 'Z001E0008', 'Z001E0002', 'Z001E0110', 'Z001E0108',
       'Z001E0107', 'Z001E0009', 'Z001E0007', 'Z002E0112', 'Z001E0006',
       'Z002E0115', 'Z002E0014', 'Z001E0003', 'Z003E0020', 'Z003E0022',
       'Z001E0106', 'Z003E0017', 'Z002E0110', 'Z002E0114', 'Z003E0019',
       'Z003E0014', 'Z002E0009', 'Z002E0007', 'Z002E0015', 'Z002E0108',
       'Z003E0013', 'Z003E0021', 'Z002E0111', 'Z001E0111', 'Z003E0016',
       'Z001E0001', 'Z002E0113', 'Z002E0011', 'Z001E0103', 'Z002E0116',
       'Z002E0117', 'Z001E0004', 'Z001E0105', 'Z002E0008', 'Z002E0109',
       'Z001E0109', 'Z002E0016', 'Z001E0010', 'Z002E0013', 'Z003E0018',
       'Z001E0005', 'Z001E0104', 'Z001E0112', 'Z002E0010', 'Z002E0012'],
      dtype='<U11')

In [8]:
#snp_ids
sim_pheno[2]

array(['PZB02058.1', 'PHM6238.36'], dtype='<U11')

In [9]:
genotypes

array([[0, 0, 0, ..., 0, 0, 0],
       [2, 2, 2, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [2, 2, 2, ..., 2, 2, 2],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 2, ..., 0, 0, 0]], dtype=int64)

In [10]:
sim_pheno

(array([ 0.07156002, -0.01397921, -0.040426  ,  0.07380458,  0.01187991,
         0.09612826,  0.09625086,  0.04699002,  0.07817087,  0.03297406,
         0.06408823,  0.09419974, -0.01122891,  0.06811163,  0.08520039,
         0.03465107, -0.08571908,  0.16946414,  0.09615379,  0.06327065,
         0.02170373,  0.1436353 ,  0.02443042,  0.00505192,  0.10594065,
         0.06625969, -0.03146853,  0.01537757,  0.07771958, -0.0260593 ,
        -0.01750206,  0.02104089,  0.09038075,  0.09998524,  0.01974403,
         0.06093298,  0.10132147,  0.08219813,  0.03286569,  0.05844026,
         0.0671134 ,  0.08452965, -0.00815651,  0.11115621,  0.06985673,
         0.01729826,  0.09325974,  0.0677881 ,  0.08690871,  0.0200444 ]),
 array(['Z003E0012', 'Z001E0008', 'Z001E0002', 'Z001E0110', 'Z001E0108',
        'Z001E0107', 'Z001E0009', 'Z001E0007', 'Z002E0112', 'Z001E0006',
        'Z002E0115', 'Z002E0014', 'Z001E0003', 'Z003E0020', 'Z003E0022',
        'Z001E0106', 'Z003E0017', 'Z002E0110', 'Z